export const SET_MOUSE_POSITION = "SET_MOUSE_POSITION";
export const UPDATE_ELEMENTS = "UPDATE_ELEMENTS";
export const SET_SELECTED_ELEMENT_ID = "SET_SELECTED_ELEMENT_ID";
export const SET_CANVAS_SIZE = "SET_CANVAS_SIZE";
