export const SET_MOUSE_POSITION = "SET_MOUSE_POSITION";
export const UPDATE_ELEMENTS = "UPDATE_ELEMENTS";
export const SET_SELECTED_ELEMENT_ID = "SET_SELECTED_ELEMENT_ID";
export const SET_HOVERED_ELEMENT_ID = "SET_HOVERED_ELEMENT_ID";
export const SET_CANVAS_SIZE = "SET_CANVAS_SIZE";
export const TOGGLE_COLOR_PANEL = "TOGGLE_COLOR_PANEL";
export const UPDATE_RECENT_COLORS = "UPDATE_RECENT_COLORS";
